services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  PhpList\RestBundle\Service\Builder\MessageBuilder:
    autowire: true
    autoconfigure: true

  PhpList\RestBundle\Service\Builder\MessageFormatBuilder:
    autowire: true
    autoconfigure: true

  PhpList\RestBundle\Service\Builder\MessageScheduleBuilder:
    autowire: true
    autoconfigure: true

  PhpList\RestBundle\Service\Builder\MessageContentBuilder:
    autowire: true
    autoconfigure: true

  PhpList\RestBundle\Service\Builder\MessageOptionsBuilder:
    autowire: true
    autoconfigure: true
