services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  PhpList\RestBundle\Common\Service\Factory\PaginationCursorRequestFactory:
    autowire: true
    autoconfigure: true
