services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  PhpList\RestBundle\Common\EventListener\ExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception }

  PhpList\RestBundle\Common\EventListener\ResponseListener:
    tags:
      - { name: kernel.event_listener, event: kernel.response }
