services:
    PhpList\Core\Domain\Messaging\MessageHandler\CampaignProcessorMessageHandler:
        autowire: true
        autoconfigure: true
        public: false

    PhpList\Core\Domain\Messaging\MessageHandler\CampaignProcessorTestMessageHandler:
        autowire: true
        autoconfigure: true
        public: false
