services:
    PhpList\Core\Domain\Messaging\MessageHandler\CampaignProcessor\CampaignProcessorMessageHandler:
        autowire: true
        autoconfigure: true
        public: false

    PhpList\Core\Domain\Messaging\MessageHandler\CampaignProcessor\TestCampaignProcessorMessageHandler:
        autowire: true
        autoconfigure: true
        public: false
