services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  _instanceof:
    Symfony\Component\Serializer\Normalizer\NormalizerInterface:
      tags: [ 'serializer.normalizer' ]

  Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter: ~

  Symfony\Component\Serializer\Normalizer\ObjectNormalizer:
    arguments:
      $classMetadataFactory: '@?serializer.mapping.class_metadata_factory'
      $nameConverter: '@Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter'

  PhpList\RestBundle\:
    resource: '../../src/*/Serializer/*'
