services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter: ~

  Symfony\Component\Serializer\Normalizer\ObjectNormalizer:
    arguments:
      $classMetadataFactory: '@?serializer.mapping.class_metadata_factory'
      $nameConverter: '@Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter'
#      $propertyTypeExtractor: '@?serializer.property_type_extractor'

  PhpList\RestBundle\Serializer\SubscriberNormalizer:
    tags: [ 'serializer.normalizer' ]
    autowire: true
