services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  PhpList\RestBundle\Service\Provider\SubscriberListProvider:
    autowire: true
    autoconfigure: true

  PhpList\RestBundle\Service\Provider\AdministratorProvider:
    autowire: true
    autoconfigure: true
