services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  PhpList\RestBundle\Common\Service\Provider\PaginatedDataProvider:
    autowire: true
    autoconfigure: true

  PhpList\RestBundle\Messaging\Service\CampaignService:
    autowire: true
    autoconfigure: true
