# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
tone_instructions: "chill"
reviews:
  profile: "chill"
  high_level_summary: true
  collapse_walkthrough: true
  suggested_labels: false
  high_level_summary_in_walkthrough: false
  changed_files_summary: false
  poem: false
  auto_review:
    enabled: true
    base_branches:
      - ".*"
    drafts: false

checks:
  docstring_coverage:
    enabled: false
