openapi: 3.0.0
info:
  title: 'My API Documentation'
  description: 'This is the OpenAPI documentation for My API.'
  contact:
    email: support@example.com
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
  version: 1.0.0
servers:
  -
    url: 'https://api.example.com'
    description: 'Production server'
  -
    url: 'https://staging-api.example.com'
    description: 'Staging server'
paths:
  /api/v2/lists:
    get:
      tags:
        - lists
      summary: 'Gets a list of all subscriber lists.'
      description: 'Returns a JSON list of all subscriber lists.'
      operationId: 88f205a115c9d929147a83720a247aae
      parameters:
        -
          name: session
          in: header
          description: 'Session ID obtained from authentication'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  properties: { name: { type: string, example: News }, description: { type: string, example: 'News (and some fun stuff)' }, creation_date: { type: string, format: date-time, example: '2016-06-22T15:01:17+00:00' }, list_position: { type: integer, example: 12 }, subject_prefix: { type: string, example: phpList }, public: { type: boolean, example: true }, category: { type: string, example: news }, id: { type: integer, example: 1 } }
                  type: object
        '403':
          description: Failure
          content:
            application/json:
              schema:
                properties:
                  message: { type: string, example: 'No valid session key was provided as basic auth password.' }
                type: object
tags:
  -
    name: lists
    description: lists
