FORMAT: 1A
HOST: https://example.com/api/v2

# phpList REST API v2


# Group Authentication

Resources related to login and logout.


## Session [/sessions]

### Create a new session (log in) [POST]

Given valid login data, this will generate a login token that will be
valid for 1 hour. It takes a JSON object containing the following key-value pairs:

+ `loginName` (string): the login name ofe the administrator to log in
+ `password` (string): the plain text password

The login token then can be passed as a `authenticationToken` cookie for requests
that require authentication.

+ Request (application/json)

    {
        "loginName": "admin",
        "password": "eetIc/Gropvoc1"
    }

+ Response 201 (application/json)

    + Body

        {
            "id": 241,
            "key": "2cfe100561473c6cdd99c9e2f26fa974",
            "expiry": "2017-07-20T18:22:48+00:00"
        }

+ Response 400 (application/json)

    + Body

        {
            "code": 1500559729794,
            "message": "No data",
            "description": "The request does not contain any data."
        }

+ Response 400 (application/json)

    + Body

        {
            "code": 1500562402438,
            "message": "Invalid JSON data",
            "description": "The data in the request is invalid JSON."
        }

+ Response 400 (application/json)

    + Body

        {
            "code": 1500562647846,
            "message": "Incomplete credentials",
            "description": "The request does not contain both loginName and password."
        }

+ Response 401 (application/json)

    + Body

        {
            "code": 1500567098798,
            "message": "Not authorized",
            "description": "The user name and password did not match any existing user."
        }
