FORMAT: 1A
HOST: https://example.com/api/v2

# phpList REST API v2


# Group Authentication

Resources related to login and logout.


## Session [/sessions]

### Create a new session (log in) [POST]

Given valid login data, this will generate a login token that will be
valid for 1 hour. It takes a JSON object containing the following key-value
pairs:

+ `loginName` (string): the login name of the superuser administrator to log in
+ `password` (string): the plain text password

Non-superuser administrators cannot authenticate via the REST API.

The login token then can be passed as basic auth password for requests
that require authentication. (The basic auth user name can be any string.)

+ Request (application/json)

    {
        "loginName": "admin",
        "password": "eetIc/Gropvoc1"
    }

+ Response 201 (application/json)

    + Body

        {
            "id": 1234,
            "key": "2cfe100561473c6cdd99c9e2f26fa974",
            "expiry": "2017-07-20T18:22:48+00:00"
        }

+ Response 400 (application/json)

    + Body

        {
            "code": 400,
            "message": "Empty JSON data"
        }

+ Response 400 (application/json)

    + Body

        {
            "code": 400,
            "message": 'Invalid json message received'
        }

+ Response 400 (application/json)

    + Body

        {
            "code": 400,
            "message": "Incomplete credentials"
        }

+ Response 401 (application/json)

    + Body

        {
            "code": 401,
            "message": "Not authorized"
        }


# Group Lists

Resources related to subscriber lists.

All requests in this group need to be authenticated with a valid session key
provided as basic auth password. (The basic auth user name can be any string.)

## Subscriber lists [/lists]

### Retrieve all subscriber lists [GET]

+ Request (application/json)

+ Response 200 (application/json)

    + Body

        {
            "name": "News",
            "description": "News (and some fun stuff)",
            "creation_date": "2016-06-22T15:01:17+00:00",
            "list_position": 12,
            "subject_prefix": "phpList",
            "public": true,
            "category": "news",
            "id": 1
        },
        {
            "name": "More news",
            "description": "",
            "creation_date": "2016-06-22T15:01:17+00:00",
            "list_position": 12,
            "subject_prefix": "",
            "public": true,
            "category": "",
            "id": 2
        }

+ Response 403 (application/json)

    + Body

        {
            "code": 403,
            "message": "No valid session key was provided as basic auth password."
        }
